### ISSUE TITLE
Installation error on Mac M1

### ISSUE THREAD

**Issue by yangbajing** [probml/probml-utils#36]
```
      error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/yangjing/miniconda3/envs/probml/include -arch arm64 -fPIC -O2 -isystem /Users/yangjing/miniconda3/envs/probml/include -arch arm64 -I/Users/yangjing/miniconda3/envs/probml/lib/python3.10/site-packages/numpy/core/include -I/Users/yangjing/miniconda3/envs/probml/include/python3.10 -c numba/_dispatcher.c -o build/temp.macosx-11.1-arm64-cpython-310/numba/_dispatcher.o" failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      /Users/yangjing/miniconda3/envs/probml/bin/python /private/var/folders/_9/xdt1l8b142z4_h7d1snnr5440000gn/T/pip-install-_w1xztsd/llvmlite_ee72896449ee4f26972d49632460a140/ffi/build.py
      LLVM version... 14.0.6

      Traceback (most recent call last):
        File "/private/var/folders/_9/xdt1l8b142z4_h7d1snnr5440000gn/T/pip-install-_w1xztsd/llvmlite_ee72896449ee4f26972d49632460a140/ffi/build.py", line 191, in <module>
          main()
        File "/private/var/folders/_9/xdt1l8b142z4_h7d1snnr5440000gn/T/pip-install-_w1xztsd/llvmlite_ee72896449ee4f26972d49632460a140/ffi/build.py", line 185, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/_9/xdt1l8b142z4_h7d1snnr5440000gn/T/pip-install-_w1xztsd/llvmlite_ee72896449ee4f26972d49632460a140/ffi/build.py", line 143, in main_posix
          raise RuntimeError(msg)
      RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '14.0.6'. Be sure to set LLVM_CONFIG to the right executable path.
      Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

      error: command '/Users/yangjing/miniconda3/envs/probml/bin/python' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built probml-utils
Failed to build numba llvmlite
ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects
```

**Comment by murphyk** [comment]
Maybe this helps? https://github.com/numba/llvmlite/issues/693

**Comment by yangbajing** [comment]
I downgraded my Python version to 3.8 and it installed fine, I was using Python 3.9 before.
